{% set name = "linkify-it-py" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 68cda27e162e9215c17d786649d1da0021a451bdc436ef9e0fa0ba5234b9b048

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - uc-micro-py

test:
  source_files:
    - test
  imports:
    - linkify_it
    - linkify_it.main
    - linkify_it.tlds
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test

about:
  home: https://github.com/tsutsu3/linkify-it-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Links recognition library with FULL unicode support. Focused on high quality link patterns detection in plain text.
  description: Links recognition library with FULL unicode support. Focused on high quality link patterns detection in plain text.
  doc_url: https://linkify-it-py.readthedocs.io
  dev_url: https://github.com/tsutsu3/linkify-it-py

extra:
  recipe-maintainers:
    - tsutsu3
    - chrisjsewell
